# Generated by Django 3.0.11 on 2020-11-15 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('prov', 'Healthcare Provider'), ('dept', ' Hospital Department'), ('team', 'Organizational team'), ('govt', 'Government'), ('ins', 'Insurance Company'), ('pay', 'Payer'), ('edu', 'Educational Institute'), ('reli', 'Religious Institution'), ('crs', 'Clinical Research Sponsor'), ('cg', 'Community Group'), ('other', 'Other')], default='prov', max_length=6)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo')),
                ('part_of', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Practioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', related_query_name='patient', to='core.HealthIdentifier')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
