# Generated by Django 3.0.11 on 2020-11-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo'),
        ),
    ]
