# Generated by Django 3.0.11 on 2020-11-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('administration', '0002_auto_20201115_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Organization'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identifier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', related_query_name='patient', to='core.HealthIdentifier'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Organization'),
        ),
        migrations.AlterField(
            model_name='practioner',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
