# Generated by Django 3.0.11 on 2020-11-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('administration', '0003_auto_20201115_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='core.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Organization'),
        ),
    ]
