# Generated by Django 3.0.11 on 2020-11-15 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20201115_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='active',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='person',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='practioner',
            name='active',
        ),
        migrations.RemoveField(
            model_name='practioner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='practioner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='practioner',
            name='person',
        ),
        migrations.RemoveField(
            model_name='practioner',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='practioner',
            name='uuid',
        ),
        migrations.AddField(
            model_name='patient',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practioner',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.Person'),
            preserve_default=False,
        ),
    ]
