# Generated by Django 3.0.11 on 2020-11-15 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20201115_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='uuid',
        ),
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='practioner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
