# Generated by Django 3.0.11 on 2020-11-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_organizationusermapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='practioner',
            name='qualification',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='practioner',
            name='speciality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='practioner',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
