# Generated by Django 3.0.11 on 2020-11-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20201120_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Organization'),
        ),
    ]
