# Generated by Django 3.0.11 on 2020-11-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, choices=[('H', 'home'), ('W', 'work'), ('T', 'temp'), ('O', 'old'), ('B', 'billing')], default='H', max_length=1)),
                ('text', models.TextField(blank=True, max_length=100)),
                ('line', models.TextField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=28)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HealthIdentifier',
            fields=[
                ('health_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('health_id_number', models.CharField(max_length=64)),
                ('health_id_provider', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, choices=[('H', 'home'), ('W', 'work'), ('T', 'temp'), ('O', 'old')], default='H', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('email', models.CharField(blank=True, max_length=64)),
                ('fax', models.CharField(blank=True, max_length=25)),
                ('social', models.ManyToManyField(blank=True, to='core.SocialAccount')),
            ],
        ),
    ]
