# Generated by Django 3.0.11 on 2020-11-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='type',
            new_name='platform',
        ),
    ]
