# Generated by Django 3.0.11 on 2020-11-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201115_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='social',
            field=models.ManyToManyField(blank=True, null=True, to='core.SocialAccount'),
        ),
    ]
